import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'

const Home: NextPage = () => {
  const fetchGalleries = async () => {
    await axios.get('https://api.imgur.com/3/gallery/r/pics', {
      headers: {
        Authorization: 'Client-ID 0e7aa0cfaccc1e1'
      }
    })
  }

  useEffect(() => {
    fetchGalleries()
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Imgur Galleries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Test
      
    </div>
  )
}

export default Home
